driver:
  name: vagrant
  driver_config:
    require_chef_omnibus: true

platforms:
- name: debian-7.9
- name: debian-8.3
- name: ubuntu-14.04
- name: ubuntu-12.04
- name: centos-6.7
- name: centos-7.2

suites:
- name: default
  run_list: [
    "apt",
    "java",
    "recipe[repose::default]",
    "recipe[repose::filter-add-header]",
    "recipe[repose::filter-api-validator]",
    "recipe[repose::filter-client-auth]",
    "recipe[repose::filter-client-authorization]",
    "recipe[repose::filter-content-type-stripper]",
    "recipe[repose::filter-derp]",
    "recipe[repose::filter-header-identity]",
    "recipe[repose::filter-header-normalization]",
    "recipe[repose::filter-header-translation]",
    "recipe[repose::filter-ip-identity]",
    "recipe[repose::filter-ip-user]",
    "recipe[repose::filter-keystone-v2]",
    "recipe[repose::filter-rackspace-auth-user]",
    "recipe[repose::filter-rate-limiting]",
    "recipe[repose::filter-slf4j-http-logging]",
    "recipe[repose::filter-translation]",
    "recipe[repose::filter-uri-identity]",
    "recipe[repose::filter-uri-stripper]",
    "recipe[repose::service-dist-datastore]",
    "recipe[repose::service-http-connection-pool]",
    "recipe[repose::service-response-messaging]"
  ]
  attributes:
    java:
      jdk_version: 7
