driver:
  name: docker
  privileged: true

platforms:
  - name: debian-7.9
  - name: debian-8.3
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-6.7
  - name: centos-7.2
    driver_config:
      image: centos:7
      provision_command: yum -y install initscripts
      run_command: /usr/sbin/init
      privileged: true
