inherit_from: .rubocop_todo.yml

Metrics/AbcSize:
  Max: 23

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/UnlessElse:
  Enabled: false
