language: ruby
rvm:
  - 2.3.6

sudo: required
services: docker

env:
  matrix:
  - TESTS="unit"
  - TESTS="rubocop"
  - TESTS="foodcritic"
  - TESTS="integration:docker[default-ubuntu-1404]"
  - TESTS="integration:docker[default-ubuntu-1204]"
  - TESTS="integration:docker[default-centos-67]"
  - TESTS="integration:docker[default-centos-72]"

before_install: curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk
install: chef exec bundle install --jobs=3 --retry=3 --without='vagrant'

# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER

script: travis_retry chef exec bundle exec rake ${TESTS}
